// ================================================================
// HOME PAGE
// - Hero slideshow
// - Global movie search
// - The visible directory below the navigation is generated by genres.js
// ================================================================

const heroImages = [
  "./assets/hero/e1.jpg",
  "./assets/hero/e2.jpg",
  "./assets/hero/e3.png",
  "./assets/hero/e4.webp",
  "./assets/hero/e5.jpg"
];

// Preserve old links such as index.html?letter=B.
// They now belong under the new “按首字母” section.
const legacyParams = new URLSearchParams(location.search);
const legacyLetter = (legacyParams.get("letter") || "").toUpperCase();

if (/^[A-Z]$/.test(legacyLetter)) {
  location.replace(
    legacyLetter === "A"
      ? "./alphabet.html"
      : `./alphabet.html?letter=${encodeURIComponent(legacyLetter)}`
  );
} else {
  const titleAliases = {
    "Unexpected": ["Ich will dich"],
    "A Woman Like Eve": ["Een vrouw als Eva"],
    "Affäre zu dritt": ["Love and Desire"],
    "Afternoon Breezes": ["Kaze-tachi no gogo", "風たちの午後"],
    "Aimée & Jaguar": ["Aimée and Jaguar"],
    "All the Silence": ["Todo el silencio"],
    "Anaïs in Love": ["Les Amours d'Anaïs"],
    "Attachment": ["Natten har øjne"]
  };

  const allMovies = Object.values(window.WLW_CATALOG)
    .flatMap(group => group.movies)
    .map(movie => ({
      ...movie,
      aliases: [
        ...(titleAliases[movie.title] || []),
        ...window.getWLWAliases(movie.title)
      ]
    }));

  function navigationHref(movie) {
    return `./movie.html?title=${encodeURIComponent(movie.title)}`;
  }

  function normalizeSearchText(value) {
    return value
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/&|\band\b/g, " and ")
      .replace(/[^\p{L}\p{N}]+/gu, " ")
      .trim()
      .replace(/\s+/g, " ");
  }

  function matchesQuery(movie, query) {
    return [movie.title, ...movie.aliases]
      .map(normalizeSearchText)
      .some(name => name.includes(query));
  }

  const hero = document.querySelector("#hero");
  const slideCount = document.querySelector("#slide-count");
  const slideProgress = document.querySelector("#slide-progress");
  const searchForm = document.querySelector("#search-form");
  const searchInput = document.querySelector("#film-search");
  const searchResults = document.querySelector("#search-results");

  // Desktop mouse hover indicator for Hero navigation.
  // It does not capture clicks, so the Hero itself still receives pointer events.
  const heroArrow = document.createElement("div");

  heroArrow.setAttribute("aria-hidden", "true");

  heroArrow.style.position = "absolute";
  heroArrow.style.top = "50%";
  heroArrow.style.transform = "translateY(-50%)";

  heroArrow.style.zIndex = "20";

  heroArrow.style.display = "grid";
  heroArrow.style.placeItems = "center";

  heroArrow.style.width = "3rem";
  heroArrow.style.height = "3rem";

  heroArrow.style.borderRadius = "999px";

  heroArrow.style.background = "rgba(5, 5, 6, 0.42)";

  heroArrow.style.border =
    "1px solid rgba(247, 243, 238, 0.18)";

  heroArrow.style.color = "#f7f3ee";

  heroArrow.style.fontSize = "1.8rem";
  heroArrow.style.fontWeight = "500";
  heroArrow.style.lineHeight = "1";

  heroArrow.style.pointerEvents = "none";

  heroArrow.style.opacity = "0";

  heroArrow.style.transition =
    "opacity 140ms ease";

  heroArrow.style.backdropFilter =
    "blur(8px)";

  hero.appendChild(heroArrow);

  function showSearchResults(rawQuery) {
    const query = normalizeSearchText(rawQuery);

    searchResults.replaceChildren();

    if (!query) {
      searchResults.hidden = true;
      searchInput.setAttribute("aria-expanded", "false");
      return [];
    }

    const results = allMovies
      .filter(movie => matchesQuery(movie, query))
      .slice(0, 8);

    if (!results.length) {
      const empty = document.createElement("p");

      empty.className = "empty-result";
      empty.textContent = "没有找到匹配的电影";

      searchResults.appendChild(empty);
    } else {
      results.forEach(movie => {
        const result = document.createElement("a");

        result.className = "search-result";
        result.href = navigationHref(movie);

        result.setAttribute("role", "option");

        result.innerHTML =
          `<span>${movie.title}</span><span>${movie.year}</span>`;

        searchResults.appendChild(result);
      });
    }

    searchResults.hidden = false;

    searchInput.setAttribute(
      "aria-expanded",
      "true"
    );

    return results;
  }

  searchInput.addEventListener(
    "input",
    event => {
      showSearchResults(
        event.target.value
      );
    }
  );

  searchForm.addEventListener(
    "submit",
    event => {
      event.preventDefault();

      const results =
        showSearchResults(
          searchInput.value
        );

      if (results.length === 1) {
        location.href =
          navigationHref(
            results[0]
          );
      }
    }
  );

  document.addEventListener(
    "click",
    event => {
      if (
        !searchForm.contains(
          event.target
        )
      ) {
        searchResults.hidden = true;

        searchInput.setAttribute(
          "aria-expanded",
          "false"
        );
      }
    }
  );

  let currentSlide = 0;
  let slideTimer;

  function setHeroImage(
    index,
    direction = null
  ) {
    currentSlide =
      (
        index +
        heroImages.length
      ) %
      heroImages.length;

    hero.classList.remove(
      "is-swipe-left",
      "is-swipe-right"
    );

    if (direction) {
      void hero.offsetWidth;

      hero.classList.add(
        direction === "next"
          ? "is-swipe-left"
          : "is-swipe-right"
      );
    }

    hero.style.backgroundImage =
      `linear-gradient(180deg,rgba(19,17,24,.08),rgba(19,17,24,.18)),url("${heroImages[currentSlide]}")`;

    slideCount.textContent =
      `${String(
        currentSlide + 1
      ).padStart(
        2,
        "0"
      )} / ${String(
        heroImages.length
      ).padStart(
        2,
        "0"
      )}`;

    slideProgress.style.transform =
      `scaleX(${currentSlide + 1})`;
  }

  function restartSlideshow() {
    clearInterval(slideTimer);

    if (
      !matchMedia(
        "(prefers-reduced-motion: reduce)"
      ).matches
    ) {
      slideTimer =
        setInterval(
          () =>
            setHeroImage(
              currentSlide + 1
            ),
          5000
        );
    }
  }

  function moveSlide(direction) {
    setHeroImage(
      currentSlide +
        (
          direction === "next"
            ? 1
            : -1
        ),
      direction
    );

    restartSlideshow();
  }

  setHeroImage(0);
  restartSlideshow();

  let pointerStart = null;

  hero.addEventListener(
    "pointerdown",
    event => {
      if (
        event.target.closest(
          ".search"
        )
      ) {
        return;
      }

      pointerStart = {
        x: event.clientX,
        y: event.clientY
      };

      hero.setPointerCapture?.(
        event.pointerId
      );
    }
  );

  hero.addEventListener(
    "pointerup",
    event => {
      if (!pointerStart) {
        return;
      }

      const deltaX =
        event.clientX -
        pointerStart.x;

      const deltaY =
        event.clientY -
        pointerStart.y;

      pointerStart = null;

      const isSwipe =
        Math.abs(deltaX) >= 45 &&
        Math.abs(deltaX) >
          Math.abs(deltaY);

      // Touch / pen / mouse drag:
      // preserve the original swipe behavior.
      if (isSwipe) {
        moveSlide(
          deltaX < 0
            ? "next"
            : "previous"
        );

        return;
      }

      // Desktop mouse:
      // click Hero left/right area to change slides.
      if (
        event.pointerType ===
        "mouse"
      ) {
        const rect =
          hero.getBoundingClientRect();

        const positionX =
          event.clientX -
          rect.left;

        const ratio =
          positionX /
          rect.width;

        if (ratio <= 0.3) {
          moveSlide(
            "previous"
          );
        } else if (
          ratio >= 0.7
        ) {
          moveSlide(
            "next"
          );
        }
      }
    }
  );

  hero.addEventListener(
    "pointercancel",
    () => {
      pointerStart = null;
    }
  );

  // Desktop mouse hover:
  // show ← on the left side and → on the right side.
  hero.addEventListener(
    "pointermove",
    event => {
      if (
        event.pointerType !==
        "mouse"
      ) {
        heroArrow.style.opacity =
          "0";

        return;
      }

      // Never show the arrow on top of the search UI.
      if (
        event.target.closest(
          ".search"
        )
      ) {
        heroArrow.style.opacity =
          "0";

        return;
      }

      const rect =
        hero.getBoundingClientRect();

      const positionX =
        event.clientX -
        rect.left;

      const ratio =
        positionX /
        rect.width;

      if (ratio <= 0.3) {
        heroArrow.textContent =
          "←";

        heroArrow.style.left =
          "1.5rem";

        heroArrow.style.right =
          "auto";

        heroArrow.style.opacity =
          "1";
      } else if (
        ratio >= 0.7
      ) {
        heroArrow.textContent =
          "→";

        heroArrow.style.right =
          "1.5rem";

        heroArrow.style.left =
          "auto";

        heroArrow.style.opacity =
          "1";
      } else {
        heroArrow.style.opacity =
          "0";
      }
    }
  );

  hero.addEventListener(
    "pointerleave",
    () => {
      heroArrow.style.opacity =
        "0";
    }
  );

  hero.addEventListener(
    "keydown",
    event => {
      if (
        event.key ===
        "ArrowLeft"
      ) {
        moveSlide(
          "previous"
        );
      }

      if (
        event.key ===
        "ArrowRight"
      ) {
        moveSlide(
          "next"
        );
      }
    }
  );

  hero.tabIndex = 0;
}
