const countries=[
  {code:"AUS",count:3,flag:"au"},{code:"AUT",count:3,flag:"at"},{code:"BEL",count:1,flag:"be"},{code:"BRA",count:2,flag:"br"},{code:"CAN",count:16,flag:"ca"},{code:"DEN",count:1,flag:"dk"},{code:"ESP",count:5,flag:"es"},{code:"FIN",count:4,flag:"fi"},{code:"FRA",count:33,flag:"fr"},{code:"GEO",count:1,flag:"ge"},{code:"GER",count:20,flag:"de"},{code:"GRE",count:1,flag:"gr"},{code:"IRE",count:4,flag:"ie"},{code:"ITA",count:9,flag:"it"},{code:"MEX",count:2,flag:"mx"},{code:"NED",count:3,flag:"nl"},{code:"NOR",count:1,flag:"no"},{code:"NZL",count:1,flag:"nz"},{code:"RUS",count:2,flag:"ru"},{code:"SUI",count:1,flag:"ch"},{code:"SWE",count:5,flag:"se"},{code:"UK",count:32,flag:"gb"},{code:"USA",count:102,flag:"us"}
];
const regions=[{code:"ASIA",label:"ASIA"},{code:"SOUTH-AMERICA",label:"SOUTH AMERICA"}];
const countryField=document.querySelector("#country-field");const regionField=document.querySelector("#region-field");const countryTemplate=document.querySelector("#country-template");const regionTemplate=document.querySelector("#region-template");
const sizeClass=count=>count<=5?"size-small":count<=20?"size-medium":"size-large";

countries.forEach((country,index)=>{const node=countryTemplate.content.cloneNode(true);const button=node.querySelector(".country-orb");button.href=`./country.html?code=${encodeURIComponent(country.code)}`;button.classList.add(sizeClass(country.count));button.setAttribute("aria-label",country.code);button.style.setProperty("--flag-image",`url("https://flagcdn.com/w640/${country.flag}.png")`);button.style.setProperty("--sway-duration",`${6.8+(index%5)*.42}s`);button.style.setProperty("--sway-delay",`${(index%7)*-.27}s`);button.style.setProperty("--drift-x",`${.08+(index%4)*.025}rem`);button.style.setProperty("--drift-y",`${.07+(index%3)*.025}rem`);button.querySelector(".country-code").textContent=country.code;countryField.appendChild(node);});
regions.forEach(region=>{const node=regionTemplate.content.cloneNode(true);const button=node.querySelector(".region-crystal");button.href=`./country.html?code=${encodeURIComponent(region.code)}`;button.setAttribute("aria-label",region.label);button.querySelector(".country-code").textContent=region.label;regionField.appendChild(node);});

function addShards(button){const shapes=["polygon(50% 0,100% 100%,10% 72%)","polygon(0 0,100% 18%,64% 100%,8% 68%)","polygon(26% 0,100% 42%,68% 100%,0 73%)","polygon(0 20%,76% 0,100% 78%,30% 100%)"];for(let index=0;index<8;index+=1){const angle=Math.PI*2*index/8;const distance=95+(index%3)*25;const shard=document.createElement("span");shard.className="crystal-shard";shard.style.setProperty("--shard-shape",shapes[index%shapes.length]);shard.style.setProperty("--shard-x",`${Math.cos(angle)*distance-50}%`);shard.style.setProperty("--shard-y",`${Math.sin(angle)*distance-50}%`);shard.style.setProperty("--shard-rotation",`${index%2?-95:110}deg`);shard.style.setProperty("--shard-delay",`${index*12}ms`);button.appendChild(shard);}}

let dragState=null;let suppressClickUntil=0;
function resetDisplacedButtons(){countryField.querySelectorAll(".country-orb.is-displaced").forEach(button=>{button.classList.remove("is-displaced");button.classList.add("is-settling");button.style.setProperty("--push-x","0px");button.style.setProperty("--push-y","0px");setTimeout(()=>{button.classList.remove("is-settling");button.style.removeProperty("--push-x");button.style.removeProperty("--push-y");},360);});}
function displaceNearbyButtons(state){const draggedRect=state.originRect;const centerX=draggedRect.left+draggedRect.width/2+state.x;const centerY=draggedRect.top+draggedRect.height/2+state.y;countryField.querySelectorAll(".country-orb").forEach(button=>{if(button===state.button)return;const rect=button.getBoundingClientRect();const otherX=rect.left+rect.width/2;const otherY=rect.top+rect.height/2;let vx=otherX-centerX,vy=otherY-centerY;let distance=Math.hypot(vx,vy)||1;const contact=draggedRect.width/2+rect.width/2+10;if(distance>=contact){button.classList.remove("is-displaced");button.style.setProperty("--push-x","0px");button.style.setProperty("--push-y","0px");return;}const strength=Math.min(26,(contact-distance)*.48);button.classList.add("is-displaced");button.style.setProperty("--push-x",`${vx/distance*strength}px`);button.style.setProperty("--push-y",`${vy/distance*strength}px`);});}
function beginLongPress(button,pointerId,x,y){clearTimeout(dragState?.timer);dragState={button,pointerId,startX:x,startY:y,x:0,y:0,active:false,originRect:button.getBoundingClientRect(),timer:setTimeout(()=>{if(!dragState||dragState.button!==button)return;dragState.active=true;button.classList.add("is-dragging");button.style.setProperty("--drag-x","0px");button.style.setProperty("--drag-y","0px");navigator.vibrate?.(18);},360)};}
function moveDrag(event){if(!dragState||event.pointerId!==dragState.pointerId)return;const dx=event.clientX-dragState.startX;const dy=event.clientY-dragState.startY;if(!dragState.active){if(Math.hypot(dx,dy)>9){clearTimeout(dragState.timer);dragState=null;}return;}event.preventDefault();dragState.x=dx;dragState.y=dy;dragState.button.style.setProperty("--drag-x",`${dx}px`);dragState.button.style.setProperty("--drag-y",`${dy}px`);displaceNearbyButtons(dragState);}
function endDrag(event){if(!dragState||event.pointerId!==dragState.pointerId)return;clearTimeout(dragState.timer);const state=dragState;dragState=null;if(!state.active)return;event.preventDefault();suppressClickUntil=Date.now()+500;resetDisplacedButtons();state.button.classList.remove("is-dragging");state.button.classList.add("is-returning");state.button.style.setProperty("--drag-x",`${state.x}px`);state.button.style.setProperty("--drag-y",`${state.y}px`);requestAnimationFrame(()=>{state.button.style.setProperty("--drag-x","0px");state.button.style.setProperty("--drag-y","0px");});setTimeout(()=>{state.button.classList.remove("is-returning");state.button.style.removeProperty("--drag-x");state.button.style.removeProperty("--drag-y");},360);}
function wireLongPressDrag(field){
  field.addEventListener("pointerdown",event=>{if(event.pointerType==="touch")return;const button=event.target.closest(".country-orb,.region-crystal");if(!button)return;button.setPointerCapture?.(event.pointerId);beginLongPress(button,event.pointerId,event.clientX,event.clientY);});
  field.addEventListener("pointermove",moveDrag,{passive:false});field.addEventListener("pointerup",endDrag);field.addEventListener("pointercancel",endDrag);
  field.addEventListener("touchstart",event=>{if(event.touches.length!==1)return;const button=event.target.closest(".country-orb,.region-crystal");if(!button)return;const touch=event.touches[0];beginLongPress(button,"touch",touch.clientX,touch.clientY);},{passive:true});
  field.addEventListener("touchmove",event=>{if(!dragState||dragState.pointerId!=="touch"||event.touches.length!==1)return;const touch=event.touches[0];moveDrag({pointerId:"touch",clientX:touch.clientX,clientY:touch.clientY,preventDefault:()=>event.preventDefault()});},{passive:false});
  field.addEventListener("touchend",event=>endDrag({pointerId:"touch",preventDefault:()=>event.preventDefault()}),{passive:false});
  field.addEventListener("touchcancel",event=>endDrag({pointerId:"touch",preventDefault:()=>event.preventDefault()}),{passive:false});
}
wireLongPressDrag(countryField);

document.addEventListener("click",event=>{const button=event.target.closest(".country-orb,.region-crystal");if(!button)return;if(Date.now()<suppressClickUntil||button.classList.contains("is-dragging")||button.classList.contains("is-returning")){event.preventDefault();return;}if(button.classList.contains("is-shattering"))return;event.preventDefault();const destination=button.href;if(matchMedia("(prefers-reduced-motion: reduce)").matches){location.href=destination;return;}addShards(button);button.classList.add("is-shattering");setTimeout(()=>{location.href=destination;},620);});
